### ISSUE TITLE
DEBUG name in project

### ISSUE THREAD

**Issue by YannickSteph** [Subito-it/SBTUITestTunnel#11]
Hi, thanks for your project.

In my project, we have rename the Build Configuration,
Exemple Debug is Staging and Release is Prod.

But now, we not go into the functions of your project.
You use define DEBUG throughout your project.

Have you solution for that ?

<img width="677" alt="capture d ecran 2016-11-10 a 14 45 33" src="https://cloud.githubusercontent.com/assets/6950194/20179068/9bcc09e6-a754-11e6-960e-0cc4e2fcf253.png">

**Comment by YannickSteph** [comment]
Exemple project.

https://github.com/YannickSteph/SampleUITestsProject

When you change Build Configuration, SBTUITestTunnel not work.

**Comment by tcamin** [comment]
The problem is that the preprocessor macros for your custom build configurations are not propagated to your Pods project. As you can see in the screenshot your Staging build configuration is missing the required DEBUG=1.

<img width="1042" alt="screen shot 2016-11-11 at 11 23 07" src="https://cloud.githubusercontent.com/assets/875025/20212029/5fdfb218-a801-11e6-9e33-4d7a235cce44.png">

An easy fix would be to specify which build configurations are debug/release.

In your case the Podfile should look something like

```
use_frameworks!

project 'SampleUITestsProject', 'Prod' => :release, 'Staging' => :debug

target 'SampleUITestsProject' do
    pod 'Alamofire'
    pod 'SBTUITestTunnel/Server'
end

target 'SampleUITestsProjectTests' do
    pod 'Alamofire'
end

target 'SampleUITestsProjectUITests' do
    pod 'Alamofire'
    pod 'SBTUITestTunnel/Client'
end
```

**Comment by YannickSteph** [comment]
It works on my project thanks you !
