### ISSUE TITLE
GCDWebServer conflicts with Firebase iOS SDK

### ISSUE THREAD

**Issue by scsinke** [Subito-it/SBTUITestTunnel#141]
Resolving this package results in a build error in combination with Firebase.

[Firebase](https://github.com/firebase/firebase-ios-sdk/blob/8467858fc4cee858511380ac0f9ea5a17d007b5d/Package.swift#L198) uses the same package as SBTUITestTunnel, but a different fork. This results in the following build error: `Dependencies could not be resolved because no versions of 'gcdwebserver' match the requirement 4.0.0..<5.0.0 and root depends on 'gcdwebserver' 4.0.0..<5.0.0.`

Maybe we want to sync these forks?

**Comment by tcamin** [comment]
Hi, that's kind of a bummer because also Firebase is using a [fork of GCDWebServer](https://github.com/firebase/firebase-ios-sdk/blob/8467858fc4cee858511380ac0f9ea5a17d007b5d/Package.swift#L197). I could potentially sync the tunnel one to Firebase's one but the same problem might arise again in the future if other dependencies pin to yet another fork.

**Comment by tcamin** [comment]
Hi, can you share a sample project that replicates the issue? I created an empty project adding all firebase packages and the tunnel but got no conflict. By looking at the Package.swift it looks like Firebase's GCDWebService dependency is used in a test target which I do not expect to be needed.
