### ISSUE TITLE
The package product 'SBTUITestTunnelServer' cannot be used as a dependency of this target because it uses unsafe build flags.

### ISSUE THREAD

**Issue by ispiryan** [Subito-it/SBTUITestTunnel#147]

**Comment by tcamin** [comment]
Did you select the master branch when adding the library as described in the [documentation](https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Installation.md#installation-swift-package-manager)?

**Comment by ispiryan** [comment]
Yes I did.

**Comment by tcamin** [comment]
I just tried on a new project in Xcode 14. I created the project added the tunnel pinned to master. Added the `import SBTUITestTunnelServer + SBTUITestTunnelServer.takeOff` in the app and `import SBTUITestTunnelClient + app.launchTunnel()` in a test, and the project compiled and run the test successfully.

Did you try this in an empty project?

**Comment by ispiryan** [comment]
Yes, it works on a new project. I also tested it.
But it doesn't work on my project.

**Comment by designatednerd** [comment]
You can also pin to a specific version as outlined [on StackOverflow](https://stackoverflow.com/questions/67889931/the-package-product-mylibrary-cannot-be-used-as-a-dependency-of-this-target-be) and [the Swift Forums](https://forums.swift.org/t/override-for-unsafeflags-in-swift-package-manager/45273/3), and not necessarily force yourself to be on a branch rather than a specific commit. 

(And as far as I can tell, this is indeed an SPM limitation)

**Comment by kunimei** [comment]
thankyou

**Comment by bartzet** [comment]
Pointing to the specific commit hash fixed the issue for me.

**Comment by tcamin** [comment]
Didn't pinning to the master branch work? What about the suggestion of @designatednerd to pin to a version?
