### ISSUE TITLE
Support sending custom command

### ISSUE THREAD

**Issue by marcelofabri** [Subito-it/SBTUITestTunnel#2]
The client should be able to send a custom command (an `NSString` + `NSDictionary`) that would be handled by a registered block in the server.

**Comment by tcamin** [comment]
I didn't implement such a feature because I wanted to avoid mixing the app's code (server side) with testing code. Currently you integrate the tunnel with 2 lines (import and takeoff) which can be easily stripped off.

However I understand there could be situations where this could be helpful so I definitely will think about adding it. But let's first wait a couple of days to see if WWDC surprises us! ;)

**Comment by tcamin** [comment]
I just pushed a few changes that add support for custom commands, usage is pretty straight forward. Check the example project (SBTViewController.m and SBTUITestTunnel_Tests.m).

Enjoy!
