### ISSUE TITLE
Running tests on different devices

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#38]
@tcamin I was wondering how are you run tests on specific device types i.e on iPhone and iPad without creating different test targets, in the blog post `http://bytes.schibsted.com/year-ui-testing-xctest/` it just shows a snippet of code. 

The current implementation I have done in the UI framework is to check the device type and fail the test if it does not match the requirement, I have not seen any way to skip the test in the XCUI framework   

```swift
    private func checkTestCompatibility() {
        if app.isRunningOnIPhone {
            guard userFlow.contains([.phone]) else {
                XCTFail("Skipping iPad Test")
                return
            }
        } else {
            guard userFlow.contains([.tablet]) else {
                XCTFail("Skipping iPhone Test")
                return
            }
        }
    }
```

**Comment by tcamin** [comment]
I didn't add that to the blog post because they way we implemented its specifically tailored on our testing workflow and wasn't easy to generalize.

Anyhow what I've done is define a set of protocols (with no methods defined in it) to 'tag' the test case classes based on device type. I then swizzle XCTest's `performTest` method calling the original implementation only if the test case matches the expected protocols. By doing so only expected tests are run and no failure occurs for tests that are skipped.

Hope this hint gets you in the right direction

**Comment by Ashraf-Ali-aa** [comment]
thanks

**Comment by tcamin** [comment]
Good!
