### ISSUE TITLE
Lack of details about manual installation

### ISSUE THREAD

**Issue by tomaszmnich** [Subito-it/SBTUITestTunnel#49]
Is this all you need to do in the case of manual installation? https://github.com/Subito-it/SBTUITestTunnel/blob/master/Documentation/Installation.md#installation-manual What about GCDWebServer dependency? Could you provide more detailed manual installation instructions?

**Comment by tcamin** [comment]
I tend to answer ASAP, however due to the lack of free time this might take longer than expected. Indeed that part of the documentation could be improved, would be great if a PR comes in. The way the library is integrated in a project can be easily deducted from the sample application available in the repo.

**Comment by tcamin** [comment]
Took some time but I finally managed to update the manual installation section.

HTH
