### ISSUE TITLE
Swift Conversion

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/SBTUITestTunnel#83]
Hi @tcamin, I have been working on converting SBT to Swift on this repo https://github.com/Ashraf-Ali-aa/UITestKit, I have added support for carthage and nearly completed converting the SBTClient into swift. Currently, the framework is fully functional since it mixes Objective-C with Swift but it would be good to merge to changes back to SBT after fully converting the SBTClient pod.

**Comment by tcamin** [comment]
Hi, thanks for the feedback.

Before considering to merge back these changes could you share the motivations behind porting the classes to Swift. I thought about making the interface more swift friendly in the past, however due to time constraint I was never able to work on that.

Instead of fully porting to swift I would really prefer add swift annotations to current code (https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/improving_objective-c_api_declarations_for_swift). Did you consider this approach?

Regarding the project name change you proposed I would be probably +1.

Finally regarding Carthage support it would be nice if you could open a PR, I would merge that in right away.

**Comment by Ashraf-Ali-aa** [comment]
The main purpose of converting to Swift was so that I could contribute to the project. I am not very strong at Objective-C also the reason why I didn't use swift annotations was that I wanted to learn a bit of Objective-C while trying to convert the project. The way I have converted the project, I was checking if I haven't broken the current tests.  I'll try to get a pull request the relevant changes. Are you happy to change the project name to `UITestKit` / `UITestKitClient`/ `UITestKitServer`

**Comment by tcamin** [comment]
Hi again, that's a fun way to learn some Objective-C 😀!

I would rather prefer keeping the project in Objective-C because for this type of hack it still guarantees some dynamism and flexibility that Swift doesn't (although I'm a great Swift fan). For example I'd like to replace the http-tunnel with an IPC tunnel and that again heavily relies on C/Objective-C, so I really prefer to stick with it. Hope you understand!

Regarding the name change I'll discuss this internally with the rest of the team and get back to you soon.

**Comment by Ashraf-Ali-aa** [comment]
if your looking for ipc have a look at https://github.com/google/eDistantObject it's used in Earl Grey 2 https://github.com/google/EarlGrey/blob/earlgrey2/README.md

**Comment by tcamin** [comment]
As previously discussed I rather keep the core of the library in Objective-C due to its more flexible nature, however I started rewriting some model classes to Swift in this branch https://github.com/Subito-it/SBTUITestTunnel/tree/feature/refactoring. These are good candidates that reduce the overall number of lines.

**Comment by tcamin** [comment]
Given that swift has started to be used where applicable I will close the issue.
