### ISSUE TITLE
requestHeaders in SBTRequestMatch appears to not be working

### ISSUE THREAD

**Issue by JasonDobo** [Subito-it/SBTUITestTunnel#90]
I've installed release 6.2 and tried to use the new feature to match a header. So I tried a simple experiment and no match was found. The first line of code, matches the request. But when I add a check for a heading, in my example the "Accept-Language", there is no match.  
I assume I'm doing something wrong, can anyone help?

Matches: 
- SBTRequestMatch(url: url, method: "GET")
Not Matched: 
- SBTRequestMatch(url: url, method: "GET", requestHeaders: ["Accept-Language": "en-us"])

Headers contained in the request, taken from Charles.
```
:method: GET
:scheme: https
:path: /client
:authority: domain
accept: */*
accept-encoding: gzip, deflate, br
user-agent: app-ios/1 CFNetwork/1121.2.1 Darwin/19.2.0
accept-language: en-us
authorization: Bearer eyJraWQiOiJyblBacDZOYmgrU1I0eEtUV2Fa
```

**Comment by tcamin** [comment]
header matching is done using case sensitive regular expressions. Did you
try lower casing “Accept-Language” to match the request content?

**Comment by JasonDobo** [comment]
I had not, but I just tried the code below, and still no match. Charles shows it is hiring the real end point and failing, as the token from a earlier matched response.
`SBTRequestMatch(url: url, method: "GET", requestHeaders: ["accept-language": "en-us"])`

**Comment by tcamin** [comment]
Just to be sure, this request is not coming from a WKWebView, right? There should be an integration test that verifies the header matching and last time I checked it was passing (https://github.com/Subito-it/SBTUITestTunnel/blob/master/Example/SBTUITestTunnel_Tests/StubTests.swift#L170)

**Comment by JasonDobo** [comment]
The request is not being made by a web view. And I sure there is a test that covers it. Unfortunately I just can't get it to work. I've tried on different requests in the app and the moment I add the `requestHeader` check to any of them they stop working.

**Comment by tcamin** [comment]
If even ‘ SBTRequestMatch(url: url, method: "GET")’ doesn’t work then I suspect there’s a problem with the url. Con you share the url value and the url you’re trying to match?

**Comment by JasonDobo** [comment]
`SBTRequestMatch(url: url, method: "GET") ` works every time and has been really good, which part of why like this framework so much. 

It was only while try trying to match the header it started failing. I can’t share the real request but but it looks like this:
GET https://domain..com/client
With the following headings
accept: */*
accept-encoding: gzip, deflate, br
user-agent: app-ios/1 CFNetwork/1121.2.1 Darwin/19.2.0
accept-language: en-us
authorization: Bearer eyJraWQiOiJyblBacDZOYmgrU1I0eEtUV2Fa

What I wanted to match ideally was the user-agent and bearer headings.

**Comment by tcamin** [comment]
It would help if you could provide a sample project that replicates the
issue. I could investigate your problem further.

**Comment by JasonDobo** [comment]
I'll try to make time later to create one and see if I can reproduce the issue outside of our project.

**Comment by JasonDobo** [comment]
I created an example application that makes a network request and added SBTUITestTunnel to the UI tests. https://github.com/JasonDobo/NetworkRequests

The good news is parsing the headers works on this app just fine, but still fails in our application. So I'm guessing something is different in the cognito sdk, and it is not using Alamofire or URLRequest. So I'll close this bug.

**Comment by lyricsboy** [comment]
I too am experiencing this problem in our project. I've done a significant amount of debugging (using version 6.4.0) and have arrived at this understanding of the behavior:

* when a match using `requestHeaders` is processed, it goes through the [stubbingHeaders path](https://github.com/Subito-it/SBTUITestTunnel/blob/d9d30479a83fee822bea7b206b12418e92af2cf0/Pod/Server/Private/SBTProxyURLProtocol.m#L505-L508) in the `startLoading` method of the URLProtocol implementation.
* this creates a new URLRequest and sets the `SBTProxyURLProtocolHandledKey` on it to YES
* the request is executed using a new NSURLSession
* the URLProtocol is consulted about the new request, and since `SBTProxyURLProtocolHandledKey` is set to YES, it [returns NO from canInitWithRequest:](https://github.com/Subito-it/SBTUITestTunnel/blob/d9d30479a83fee822bea7b206b12418e92af2cf0/Pod/Server/Private/SBTProxyURLProtocol.m#L371-L375)
* the request is not stubbed and makes a network request to the real URL

I'll note that in our app, we are using Alamofire, if that makes some difference. I'm having trouble understanding how the header-based request matching is intended to work, as to me it seems like it would always try to make a real request in this situation.

**Comment by tcamin** [comment]
The stub continues in the nsurlsession delegate methods, see https://github.com/Subito-it/SBTUITestTunnel/blob/d9d30479a83fee822bea7b206b12418e92af2cf0/Pod/Server/Private/SBTProxyURLProtocol.m#L660

While this might be unexpected it is due to how NSURLProtocol is implemented: when you call .resume() on a URLSession `canInitWithRequest` is called multiple times by Foundation and the URLRequest that is passed to it doesn't immediately contain the httprequest headers. We therefore postpone matching the request headers when startLoading is called when request headers are properly populated. 

Of course I did forget about all this and started to do some refactoring getting to the same conclusion, I added some comment for the future me 😂.

I pushed the changes to 11fa1b42e944b6b603da8a955deb906b71bcc1e8. Implementation wise nothing changes but I cleaned up some code duplication and it should be easier to move the request header matching to the SBTRequestMatch matching method.

If you find a workaround to improve this behaviour please let me know.

**Comment by lyricsboy** [comment]
Thanks for your detailed explanation, @tcamin! The part I'm still uncertain about is how the request that is initiated inside the `SBTProxyURLProtocol.startLoading` implementation is intercepted and stubbed. In my testing that request will still hit the live server.

**Comment by tcamin** [comment]
For a request that stubs or matchers request/response headers:

1. URLProtocol intercepts your _requestA_ and returns `YES` in `canInitWithRequest:` if it matches requests rules (ignoring request/response header rules).
2. `startLoading` is called, the `if (stubRule && !stubbingHeaders) {` is skipped, on line 515 we instantiate a new NSURLSession (_urlSessionA_) that has request (_requestB_) that is a copy of the original _requestA_. This new request is tagged with `SBTProxyURLProtocolHandledKey` so that it is not processed by NSURLProtocol when the NSURLSession will resume.
3. The NSURLProtocol is set as a delegate of the _urslSessionA_.
4. The NSURLProtocol is resumed (line 542).
5. URLSession:dataTask:didReceiveResponse:completionHandler: is called
there we check if the _requestA_ has to be stubbed if it does we complete the request with stub data, otherwise we proceed with the request normally (lines 697-704).

**Comment by lyricsboy** [comment]
Thanks. I think that aligns with my understanding of the behavior as well, but: is it true that by the time `URLSession:dataTask:didReceiveResponse:completionHandler:` is called, the URLSession has actually made a real request to the server? In my testing that appears to be what's happening, and the response is `401 Unauthorized` from our service because we are not authenticated (as expected).
